# Generated by Django 2.2.7 on 2019-11-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.CharField(max_length=23)),
                ('any_thing_to_say', models.CharField(max_length=34)),
            ],
        ),
    ]
